#!/system/bin/sh
# raidenTweaks™ is a simple kernel tweaker.
# Copyright (C) 2021~2024  Raiden Ishigami <contact.raidenishi69@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   any later version.
#
# This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.

# Print an empty line
echo ""

# Directories and files to delete
clean_list=(
  "/data/*.log"
  "/data/vendor/wlan_logs"
  "/data/*.txt"
  "/cache/*.apk"
  "/data/anr/*"
  "/data/backup/pending/*.tmp"
  "/data/cache/*.*"
  "/data/data/*.log"
  "/data/data/*.txt"
  "/data/log/*.log"
  "/data/log/*.txt"
  "/data/local/*.apk"
  "/data/local/*.log"
  "/data/local/*.txt"
  "/data/mlog/*"
  "/data/system/*.log"
  "/data/system/*.txt"
  "/data/system/dropbox/*"
  "/data/system/usagestats/*"
  "/data/system/shared_prefs/*"
  "/data/tombstones/*"
  "/data/media/0/LOST.DIR"
  "/data/media/0/found000"
  "/data/media/0/LazyList"
  "/data/media/0/albumthumbs"
  "/data/media/0/kunlun"
  "/data/media/0/.CacheOfEUI"
  "/data/media/0/.bstats"
  "/data/media/0/.taobao"
  "/data/media/0/Backucup"
  "/data/media/0/MIUI/debug_log"
  "/data/media/0/ramdump"
  "/data/media/0/UnityAdsVideoCache"
  "/data/media/0/*.log"
  "/data/media/0/*.CHK"
  "/data/media/0/duilite"
  "/data/media/0/DkMiBrowserDemo"
  "/data/media/0/.xlDownload"
)

# Loop through the files and directories and delete them
for item in "${clean_list[@]}"
do
  if [[ -e "$item" ]]; then
    rm -rf $item
  fi
done

# Print an empty line
echo ""

# Always return last command exit status
exit